[build]
  command = "rm -rf dist && mkdir -p dist && unzip -q release/portal.zip -d dist"
  publish = "dist"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/area-do-aluno/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/pagamento/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
