import { createClient } from 'npm:@supabase/supabase-js@2.57.0'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const rawSecrets=Deno.env.get('SUPABASE_SECRET_KEYS')
const SERVICE_KEY=rawSecrets?JSON.parse(rawSecrets)['default']:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const PORTAL_ORIGIN='https://www.liveconnect.com.br'
const BRIDGE='https://kvwsqfnyebyjncfgvqnd.supabase.co/functions/v1/liveconnect-mercadopago-bridge'
const allowedOrigins=new Set([PORTAL_ORIGIN,'https://liveconnect.com.br','https://portallc.netlify.app'])
function originAllowed(origin:string){return !origin||allowedOrigins.has(origin)||origin.startsWith('http://localhost:')||origin.startsWith('http://127.0.0.1:')||/^https:\/\/[a-z0-9-]+--portallc\.netlify\.app$/i.test(origin)}
function headers(req:Request){const origin=req.headers.get('origin')||'';return {'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':originAllowed(origin)&&origin?origin:PORTAL_ORIGIN,'Vary':'Origin','Access-Control-Allow-Headers':'content-type, apikey, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store, max-age=0'}}
const reply=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:headers(req)})
const uuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))?String(v):''
const money=(v:unknown)=>Math.round(Number(v||0)*100)/100
const mode=(v:unknown)=>String(v||'')==='profissao_rapida'?'profissao_rapida':'tradicional'
function brazilDateParts(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=(t:string)=>Number(parts.find(p=>p.type===t)?.value||0);return {y:get('year'),m:get('month'),d:get('day')}}
function nextDueDate(day:number){const {y,m,d}=brazilDateParts();let yy=y,mm=m;if(d>day){mm++;if(mm>12){mm=1;yy++}}const last=new Date(Date.UTC(yy,mm,0)).getUTCDate();return `${yy}-${String(mm).padStart(2,'0')}-${String(Math.min(day,last)).padStart(2,'0')}`}
async function ensureContext(supabase:any,leadId:string,interestId:string,commercialMode:string){
 const {data:interest,error:ie}=await supabase.from('lead_interests').select('id,lead_id,course_id,interest_type,metadata').eq('id',interestId).eq('lead_id',leadId).maybeSingle();if(ie)throw ie;if(!interest||interest.interest_type!=='matricula_portal'||!interest.course_id)throw new Error('payment_context_not_found')
 const {data:lead,error:le}=await supabase.from('leads').select('id,full_name,whatsapp,email').eq('id',leadId).is('deleted_at',null).maybeSingle();if(le)throw le;if(!lead)throw new Error('lead_not_found');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(lead.email||'').trim()))throw new Error('email_required_for_automatic_enrollment')
 const {data:course,error:ce}=await supabase.from('courses').select('id,name,type,active').eq('id',interest.course_id).maybeSingle();if(ce)throw ce;if(!course||course.type!=='pago'||course.active!==true)throw new Error('course_not_payable')
 const {data:offer,error:oe}=await supabase.rpc('public_portal_commercial_offer',{p_course_name:course.name});if(oe)throw oe;const o=Array.isArray(offer)?offer[0]:offer;if(!o)throw new Error('active_pricing_not_found')
 const ef=money(o.enrollment_fee),mf=money(o.monthly_price),inst=Math.max(1,Number(o.installments||1)),fastTotal=money(o.fast_track_total),stdTotal=money(o.standard_total)
 let {data:enrollment,error:ee}=await supabase.from('enrollments').select('*').eq('lead_id',leadId).eq('course_id',course.id).is('cancelled_at',null).order('enrolled_at',{ascending:false}).limit(1).maybeSingle();if(ee)throw ee
 const meta=interest.metadata||{};const due=Number(meta.due_day||0)||null;const schedule=String(meta.schedule_text||'').trim()||null;const dueDate=due?nextDueDate(due):null
 if(!enrollment){
  const fast=commercialMode==='profissao_rapida';const {data:created,error:ne}=await supabase.from('enrollments').insert({lead_id:leadId,course_id:course.id,enrollment_fee_snapshot:fast?0:ef,first_monthly_fee_snapshot:fast?0:mf,monthly_fee_snapshot:mf,enrollment_payment_status:'pendente',first_month_payment_status:fast?'isento':'pendente',due_day:due,first_month_due_date:fast?null:dueDate,schedule_text:schedule,commercial_mode:commercialMode,installments_snapshot:inst,course_total_snapshot:fast?fastTotal:stdTotal,note:fast?'Profissão Rápida — valor integral contratado no cartão; matrícula isenta':'Modalidade tradicional — matrícula obrigatória; 1ª mensalidade opcional'}).select('*').single();if(ne)throw ne;enrollment=created
  const rows=fast?[{enrollment_id:enrollment.id,kind:'profissao_rapida_total',amount:fastTotal,status:fastTotal<=0?'isento':'pendente'}]:[{enrollment_id:enrollment.id,kind:'matricula',amount:ef,status:ef<=0?'isento':'pendente'},{enrollment_id:enrollment.id,kind:'primeira_mensalidade',amount:mf,status:mf<=0?'isento':'pendente'}];const {error:pErr}=await supabase.from('payments').insert(rows);if(pErr)throw pErr
 }else{
  const {data:paid}=await supabase.from('payments').select('id').eq('enrollment_id',enrollment.id).eq('status','pago').limit(1);if((paid||[]).length===0&&enrollment.commercial_mode!==commercialMode){await supabase.from('payments').delete().eq('enrollment_id',enrollment.id).eq('status','pendente');const fast=commercialMode==='profissao_rapida';await supabase.from('enrollments').update({commercial_mode:commercialMode,enrollment_fee_snapshot:fast?0:ef,first_monthly_fee_snapshot:fast?0:mf,monthly_fee_snapshot:mf,installments_snapshot:inst,course_total_snapshot:fast?fastTotal:stdTotal,enrollment_payment_status:'pendente',first_month_payment_status:fast?'isento':'pendente',first_month_due_date:fast?null:dueDate}).eq('id',enrollment.id);const rows=fast?[{enrollment_id:enrollment.id,kind:'profissao_rapida_total',amount:fastTotal,status:'pendente'}]:[{enrollment_id:enrollment.id,kind:'matricula',amount:ef,status:ef<=0?'isento':'pendente'},{enrollment_id:enrollment.id,kind:'primeira_mensalidade',amount:mf,status:mf<=0?'isento':'pendente'}];await supabase.from('payments').insert(rows);enrollment={...enrollment,commercial_mode:commercialMode,enrollment_fee_snapshot:fast?0:ef,monthly_fee_snapshot:mf,installments_snapshot:inst,course_total_snapshot:fast?fastTotal:stdTotal,first_month_due_date:fast?null:dueDate}}
 }
 await supabase.from('lead_interests').update({metadata:{...(interest.metadata||{}),commercial_mode:commercialMode,commercial_offer:{enrollment_fee:ef,monthly_price:mf,installments:inst,standard_total:stdTotal,fast_track_total:fastTotal,fast_track_savings:Number(o.fast_track_savings||0),campaign_name:o.campaign_name||null}}}).eq('id',interestId)
 const {data:payments,error:pre}=await supabase.from('payments').select('id,kind,amount,status').eq('enrollment_id',enrollment.id).order('created_at',{ascending:true});if(pre)throw pre
 return {lead,interest,course,enrollment,payments:payments||[],offer:o}
}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:headers(req)});if(req.method!=='POST')return reply(req,{ok:false,error:'method_not_allowed'},405);const origin=req.headers.get('origin')||'';if(!originAllowed(origin))return reply(req,{ok:false,error:'origin_not_allowed'},403)
 try{const body=await req.json().catch(()=>({}));const action=String(body.action||'create');const commercialMode=mode(body.commercial_mode);const supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
  if(action==='status'){const token=uuid(body.token);if(!token)return reply(req,{ok:false,error:'invalid_token'},400);const {data:s}=await supabase.from('payment_checkout_sessions').select('*').eq('public_token',token).maybeSingle();if(!s)return reply(req,{ok:false,error:'checkout_not_found'},404);const {data:e}=await supabase.from('enrollments').select('course_id,commercial_mode,enrollment_payment_status,first_month_payment_status,first_month_due_date,installments_snapshot').eq('id',s.enrollment_id).maybeSingle();let courseName='Formação Live Connect';if(e?.course_id){const {data:c}=await supabase.from('courses').select('name').eq('id',e.course_id).maybeSingle();if(c?.name)courseName=c.name}return reply(req,{ok:true,token:s.public_token,course_name:courseName,amount:Number(s.amount),currency:s.currency,status:s.status,paid_at:s.paid_at||null,expires_at:s.expires_at||null,init_point:s.init_point||null,commercial_mode:e?.commercial_mode||'tradicional',installments:e?.installments_snapshot||null,enrollment_payment_status:e?.enrollment_payment_status||null,first_month_payment_status:e?.first_month_payment_status||null,first_month_due_date:e?.first_month_due_date||null})}
  if(!['quote','create'].includes(action))return reply(req,{ok:false,error:'invalid_action'},400);const leadId=uuid(body.lead_id),interestId=uuid(body.interest_id);if(!leadId||!interestId)return reply(req,{ok:false,error:'invalid_context'},400)
  let ctx:any;try{ctx=await ensureContext(supabase,leadId,interestId,commercialMode)}catch(e){const m=e instanceof Error?e.message:String(e);return reply(req,{ok:false,error:m},500)}
  const fast=commercialMode==='profissao_rapida',matricula=ctx.payments.find((p:any)=>p.kind==='matricula'),monthly=ctx.payments.find((p:any)=>p.kind==='primeira_mensalidade'),fastPay=ctx.payments.find((p:any)=>p.kind==='profissao_rapida_total');const q={ok:true,enrollment_id:ctx.enrollment.id,course_name:ctx.course.name,commercial_mode:commercialMode,enrollment_fee:fast?0:Number(matricula?.amount||ctx.offer.enrollment_fee||0),monthly_fee:Number(ctx.offer.monthly_price||0),installments:Number(ctx.offer.installments||0),standard_total:Number(ctx.offer.standard_total||0),fast_track_total:Number(ctx.offer.fast_track_total||0),fast_track_savings:Number(ctx.offer.fast_track_savings||0),campaign_name:ctx.offer.campaign_name||null,first_month_due_date:ctx.enrollment.first_month_due_date||null,enrollment_required:true,monthly_optional:!fast,card_only:fast}
  if(action==='quote')return reply(req,q)
  const includeMonthly=!fast&&body.include_first_monthly===true;const payable=fast?[fastPay].filter((p:any)=>p&&p.status==='pendente'&&Number(p.amount)>0):ctx.payments.filter((p:any)=>p.status==='pendente'&&Number(p.amount)>0&&(p.kind==='matricula'||(includeMonthly&&p.kind==='primeira_mensalidade')))
  if(!payable.length)return reply(req,{...q,already_settled:true,amount:0});const amount=money(payable.reduce((s:number,p:any)=>s+Number(p.amount||0),0)),scope=fast?'profissao_rapida':includeMonthly?'initial':'enrollment',cutoff=new Date(Date.now()-15*60*1000).toISOString();const {data:recent}=await supabase.from('payment_checkout_sessions').select('*').eq('enrollment_id',ctx.enrollment.id).eq('scope',scope).in('status',['created','pending']).gte('created_at',cutoff).order('created_at',{ascending:false}).limit(1).maybeSingle();if(recent?.init_point&&money(recent.amount)===amount)return reply(req,{...q,reused:true,token:recent.public_token,amount,init_point:recent.init_point,expires_at:recent.expires_at,breakdown:payable.map((p:any)=>({kind:p.kind,amount:Number(p.amount)}))})
  const expiresAt=new Date(Date.now()+48*60*60*1000);const {data:session,error:se}=await supabase.from('payment_checkout_sessions').insert({enrollment_id:ctx.enrollment.id,lead_id:leadId,scope,amount,currency:'BRL',status:'created',expires_at:expiresAt.toISOString(),metadata:{interest_id:interestId,course_id:ctx.course.id,payment_ids:payable.map((p:any)=>p.id),payment_kinds:payable.map((p:any)=>p.kind),commercial_mode:commercialMode,installments:Number(ctx.offer.installments||0)}}).select('*').single();if(se)throw se
  let bd:any=null,bridgeErr:any=null;try{const rr=await supabase.rpc('portal_mp_bridge_create',{p_token:session.public_token});bd=rr.data;bridgeErr=rr.error}catch(e){bridgeErr=e}
  const {data:saved,error:savedErr}=await supabase.from('payment_checkout_sessions').select('*').eq('id',session.id).maybeSingle();
  if(saved?.status==='pending'&&saved?.init_point){return reply(req,{...q,token:saved.public_token,amount:Number(saved.amount),status:'pending',init_point:saved.init_point,expires_at:saved.expires_at||expiresAt.toISOString(),breakdown:payable.map((p:any)=>({kind:p.kind,amount:Number(p.amount)}))})}
  if(savedErr||bridgeErr||!bd?.ok){const providerError=savedErr?{error:savedErr.message}:bridgeErr?{error:bridgeErr instanceof Error?bridgeErr.message:String(bridgeErr)}:bd;await supabase.from('payment_checkout_sessions').update({status:'error',metadata:{...session.metadata,provider_error:providerError}}).eq('id',session.id);return reply(req,{ok:false,error:'provider_error',message:String(bd?.message||bd?.error||(bridgeErr instanceof Error?bridgeErr.message:bridgeErr)||savedErr?.message||'Não foi possível iniciar o pagamento.')},502)}
  const initPoint=bd.init_point||bd.sandbox_init_point||null;return reply(req,{...q,token:session.public_token,amount,status:'pending',init_point,expires_at:expiresAt.toISOString(),breakdown:payable.map((p:any)=>({kind:p.kind,amount:Number(p.amount)}))})
 }catch(error){console.error('portal-payment-v5',error);return reply(req,{ok:false,error:'internal_error'},500)}})