import { createClient } from 'npm:@supabase/supabase-js@2.57.0'
const PORTAL_ORIGIN='https://www.liveconnect.com.br'
const allowedOrigins=new Set([PORTAL_ORIGIN,'https://liveconnect.com.br','https://portallc.netlify.app'])
function originAllowed(origin:string){return !origin||allowedOrigins.has(origin)||origin.startsWith('http://localhost:')||origin.startsWith('http://127.0.0.1:')||/^https:\/\/[a-z0-9-]+--portallc\.netlify\.app$/i.test(origin)}
function cors(req:Request){const origin=req.headers.get('origin')||'';return {'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':originAllowed(origin)&&origin?origin:PORTAL_ORIGIN,'Vary':'Origin','Access-Control-Allow-Headers':'content-type, apikey, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store, max-age=0'}}
const dueDays=new Set([5,10,15,20,25,30]);const modalities=new Set(['Presencial','EAD']);const instructionModels=new Set(['padrao','professor_em_sala'])
const digits=(v:unknown)=>String(v??'').replace(/\D/g,'');const text=(v:unknown,max=300)=>String(v??'').trim().slice(0,max);const email=(v:unknown)=>{const s=text(v,180).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:''};const uuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))?String(v):''
const reply=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors(req)})
function calcAge(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const [y,m,d]=value.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1,d,12));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d)return null;const now=new Date();let age=now.getUTCFullYear()-y;const md=now.getUTCMonth()+1-m;if(md<0||(md===0&&now.getUTCDate()<d))age--;return age}
function validCpf(value:string){const cpf=digits(value);if(cpf.length!==11||/^(\d)\1{10}$/.test(cpf))return false;const calc=(base:number)=>{let sum=0;for(let i=0;i<base;i++)sum+=Number(cpf[i])*(base+1-i);const r=(sum*10)%11;return r===10?0:r};return calc(9)===Number(cpf[9])&&calc(10)===Number(cpf[10])}
const dayName=(n:number)=>({1:'Segunda-feira',2:'Terça-feira',3:'Quarta-feira',4:'Quinta-feira',5:'Sexta-feira',6:'Sábado'} as Record<number,string>)[n]||`Dia ${n}`
const hh=(v:string)=>String(v||'').slice(0,5)
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,{ok:false,error:'method_not_allowed'},405)
 const origin=req.headers.get('origin')||'';if(!originAllowed(origin))return reply(req,{ok:false,error:'origin_not_allowed'},403)
 try{
  const body=await req.json();if(text(body.website,200))return reply(req,{ok:true});const courseType=body.course_type==='gratuito'?'gratuito':'pago';const courseName=text(body.course_name,180),fullName=text(body.full_name,160),whatsapp=digits(body.whatsapp),studentEmail=email(body.email);if(!courseName||fullName.length<3||whatsapp.length<10||whatsapp.length>13)return reply(req,{ok:false,error:'basic_data_invalid'},400);if(courseType==='pago'&&!studentEmail)return reply(req,{ok:false,error:'email_required'},400);if(body.email&&!studentEmail)return reply(req,{ok:false,error:'invalid_email'},400)
  const url=Deno.env.get('SUPABASE_URL')!;const raw=Deno.env.get('SUPABASE_SECRET_KEYS');const secret=raw?JSON.parse(raw)['default']:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const supabase=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}})
  let modality=courseType==='gratuito'?'Presencial':text(body.modality,20);if(!modalities.has(modality))return reply(req,{ok:false,error:'invalid_modality'},400);let instructionModel=text(body.instruction_model,30)||'padrao';if(!instructionModels.has(instructionModel))instructionModel='padrao';if(modality==='EAD')instructionModel='padrao'
  let preferredClassId:string|null=null,preferredWeekday:number|null=null,preferredStart:string|null=null,preferredEnd:string|null=null,scheduleText='EAD - sem horário presencial',remainingSnapshot:number|null=null
  if(modality==='Presencial'){
    preferredClassId=uuid(body.preferred_class_id)||null;if(!preferredClassId)return reply(req,{ok:false,error:'class_preference_required'},400)
    const {data:cl,error:clErr}=await supabase.from('class_capacity_summary').select('id,weekday,start_time,end_time,status,remaining_seats,source_hidden').eq('id',preferredClassId).maybeSingle();if(clErr)throw clErr
    if(!cl||String(cl.status)!=='aberta'||cl.source_hidden===true)return reply(req,{ok:false,error:'class_unavailable'},409);remainingSnapshot=Number(cl.remaining_seats||0);if(remainingSnapshot<=0)return reply(req,{ok:false,error:'class_full'},409)
    preferredWeekday=Number(cl.weekday);preferredStart=String(cl.start_time);preferredEnd=String(cl.end_time);scheduleText=`${dayName(preferredWeekday)} • ${hh(preferredStart)} às ${hh(preferredEnd)}`
  }
  let courseId:string|null=null;const {data:matched}=await supabase.from('courses').select('id').ilike('name',courseName).eq('type',courseType).eq('active',true).limit(1);if(matched?.length)courseId=matched[0].id
  let birthDate:string|null=null,age:number|null=null,isMinor:boolean|null=null,studentRg:string|null=null,studentCpf:string|null=null,guardianName:string|null=null,guardianRg:string|null=null,guardianCpf:string|null=null,guardianBirthDate:string|null=null,zipCode:string|null=null,street:string|null=null,number:string|null=null,neighborhood:string|null=null,city:string|null=null,stateCode:string|null=null,dueDay:number|null=null
  if(courseType==='pago'){
    birthDate=text(body.birth_date,10);age=calcAge(birthDate);if(age===null||age<5||age>100)return reply(req,{ok:false,error:'invalid_birth_date'},400);isMinor=age<18;zipCode=digits(body.zip_code);street=text(body.street,180);number=text(body.number,30);neighborhood=text(body.neighborhood,120);city=text(body.city,120);stateCode=text(body.state,2).toUpperCase();if(zipCode.length!==8||!street||!number||!neighborhood||!city||!/^[A-Z]{2}$/.test(stateCode))return reply(req,{ok:false,error:'invalid_address'},400)
    studentRg=text(body.rg,20).replace(/[^0-9A-Za-z]/g,'')||null;studentCpf=digits(body.cpf)||null;if(!isMinor&&((studentRg?.length??0)<5||!validCpf(studentCpf||'')))return reply(req,{ok:false,error:'adult_documents_invalid'},400)
    if(isMinor){guardianName=text(body.guardian_name,160);guardianRg=text(body.guardian_rg,20).replace(/[^0-9A-Za-z]/g,'');guardianCpf=digits(body.guardian_cpf);guardianBirthDate=text(body.guardian_birth_date,10);const ga=calcAge(guardianBirthDate);if(guardianName.length<3||guardianRg.length<5||!validCpf(guardianCpf)||ga===null||ga<18)return reply(req,{ok:false,error:'guardian_data_invalid'},400)}
    dueDay=Number(body.due_day);if(!dueDays.has(dueDay))return reply(req,{ok:false,error:'invalid_due_day'},400)
  }
  const {data:existingLead,error:lookupError}=await supabase.from('leads').select('id,status').eq('whatsapp',whatsapp).is('deleted_at',null).limit(1).maybeSingle();if(lookupError)throw lookupError
  const common:Record<string,unknown>={full_name:fullName,whatsapp,landing_page:text(body.landing_page,300),referrer:text(body.referrer,300),utm_source:text(body.utm_source,120)||null,utm_medium:text(body.utm_medium,120)||null,utm_campaign:text(body.utm_campaign,120)||null,updated_at:new Date().toISOString()};if(courseType==='pago')Object.assign(common,{age,birth_date:birthDate,address:`${street}, ${number} - ${city}/${stateCode}`,neighborhood,zip_code:zipCode,rg:isMinor?null:studentRg,cpf:isMinor?null:studentCpf,guardian_name:isMinor?guardianName:null,guardian_rg:isMinor?guardianRg:null,guardian_cpf:isMinor?guardianCpf:null,guardian_birth_date:isMinor?guardianBirthDate:null})
  if(studentEmail)common.email=studentEmail;let leadId:string;if(existingLead?.id){const {error}=await supabase.from('leads').update(common).eq('id',existingLead.id);if(error)throw error;leadId=existingLead.id}else{const {data,error}=await supabase.from('leads').insert({...common,status:'pre_inscricao',source:'portal_liveconnect'}).select('id').single();if(error)throw error;leadId=data.id}
  const interestType=courseType==='gratuito'?'curso_gratuito_portal':'matricula_portal',cutoff=new Date(Date.now()-45000).toISOString();const {data:recent}=await supabase.from('lead_interests').select('id').eq('lead_id',leadId).eq('interest_type',interestType).gte('created_at',cutoff).limit(1);if(recent?.length)return reply(req,{ok:true,lead_id:leadId,interest_id:recent[0].id,duplicate:true,preserved_status:!!existingLead?.id})
  const submittedAt=new Date().toISOString();const metadata=courseType==='pago'?{form_version:6,course_name:courseName,course_type:courseType,modality,instruction_model:instructionModel,due_day:dueDay,schedule_text:scheduleText,preferred_class_id:preferredClassId,preferred_weekday:preferredWeekday,preferred_start_time:preferredStart,preferred_end_time:preferredEnd,remaining_seats_snapshot:remainingSnapshot,preference_only:true,student:{full_name:fullName,age,birth_date:birthDate,whatsapp,email:studentEmail||null,rg:isMinor?null:studentRg,cpf:isMinor?null:studentCpf,address:{zip_code:zipCode,street,number,neighborhood,city,state:stateCode}},guardian:isMinor?{full_name:guardianName,rg:guardianRg,cpf:guardianCpf,birth_date:guardianBirthDate}:null,submitted_at:submittedAt}:{form_version:6,course_name:courseName,course_type:courseType,modality:'Presencial',schedule_text:scheduleText,preferred_class_id:preferredClassId,preference_only:true,student:{full_name:fullName,whatsapp},submitted_at:submittedAt}
  const {data:interest,error:interestError}=await supabase.from('lead_interests').insert({lead_id:leadId,course_id:courseId,interest_type:interestType,source:'portal_liveconnect',metadata}).select('id').single();if(interestError)throw interestError
  const description=courseType==='gratuito'?`${courseName} — curso gratuito presencial`:`${courseName} — ${modality}${instructionModel==='professor_em_sala'?' — professor em sala':''}${modality==='Presencial'?` — preferência: ${scheduleText}`:''} — vencimento dia ${dueDay}`;const {error:activityError}=await supabase.from('lead_activities').insert({lead_id:leadId,activity_type:courseType==='gratuito'?'inscricao_gratuita_portal':'ficha_matricula_portal',description,metadata:{interest_id:interest.id,course_id:courseId,modality,instruction_model:instructionModel,due_day:dueDay,schedule_text:scheduleText,preferred_class_id:preferredClassId,preference_only:true}});if(activityError)throw activityError
  return reply(req,{ok:true,lead_id:leadId,interest_id:interest.id,preserved_status:!!existingLead?.id,preferred_class_id:preferredClassId,schedule_text:scheduleText})
 }catch(error){console.error('portal-enrollment-submit',error);return reply(req,{ok:false,error:'internal_error'},500)}
})